config/routes.rb
Crossroad::Application.routes.draw do
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :categories
  resources :articles
  resources :projects
  resources :events
  resources :places

  namespace :api do
    match '/type_list', :action => "type_list", :via => [:get, :post, :options], :format => "json"
    match '/new_type', :action => "new_type", :via => [:get, :post, :options], :format => "json"
    match '/content', :action => "content", :via => [:get, :post, :options], :format => "json"
    match '/points', :action => "points", :via => [:get, :post, :options], :format => "json"
  end

  root :to => 'main#index'

  
  match "template", :controller => 'main', :action => 'template'
  match "category_template", :controller => 'main', :action => 'category_template'

  match "section/(:section_type)", :controller => 'main', :action => 'section', :as => :section
  match "make_new_one", :controller => 'main', :action => 'form', :as => :main_form
  match "map", :controller => 'main', :action => 'map', :as => :map

end

app/controllers/main_controller.rb
#encoding: utf-8
class MainController < ApplicationController
  #protect_from_forgery
  before_filter :sections_init
  def index
  end

  def search
    @categories = Category.main
  end

  def map
    @filters = {}
    if @section
      @types = Type.where(:section_type => @section[0])
      @filters = {section_type: @section[0]}
      #todo limit
      @content = eval(@section[0].humanize).all
      #set_gon_points
      puts 'points', set_gon_points().inspect
    else
      place_ids = Place.all.map(&:id) + Event.all.map(&:place_id)
      gon.points = Place.get_info_for_all place_ids
      #set_gon_points
      puts 'points', gon.points
    end
    @categories = Category.main

  end

  def section
    @categories = Category.main
    @types = Type.where(:section_type => @section[0])
    @filters = {section_type: @section[0]}
    #todo limit
    @content = @content_class.order(:created_at).page(params[:page]).per(9)
    puts @section[0]

    puts 'points', set_gon_points(@content_class).inspect
  end

  def form
    puts params.inspect 
    if params[:element]
      @error = false
      element = params[:element]
      parameters = {
        :category_id => element[:category_id],
        :type_id     => element[:type_id],
        :name        => element[:name],
        :picture     => element[:picture]
      }
      case element[:section]
      when "article"
        article = element[:article]
        parameters.merge!( {
          :autor   => article[:autor],
          :body    => article[:body],
          :sources => article[:sources]
        })
      when "event"
        event = element[:event]
        parameters.merge!({
          :start_at  => event[:start_at],
          :end_at    => event[:end_at],
          :description => event[:description],
          :web_links   => event[:web_links]
        })
      when "project"
        project = element[:project]
        parameters.merge!({
          :description => project[:description],
          :web_links   => project[:web_links]
        })
      when "place"
        place = element[:place]
        parameters.merge!({
          :description => place[:description],
          :web_links   => place[:web_links]
        })
      else
        flash[:error] = 'Неизвестный тип объекта. Повторите попытку.'
        @error = true
      end
      #creation of the some thing
      # puts @error
      # puts flash.inspect
      unless @error
        class_obj = eval(element[:section].humanize)
        @thing = class_obj.new(parameters)
        if @thing.save
          redirect_to @thing
        else
          flash[:error] = 'Допущена ошибка. повторите попытку1'
        end
      else
        flash[:error] = 'Допущена ошибка. повторите попытку2'
      end
    end
  end

  private
    def sections_init
      @sections = SECTIONS
      @section = SECTIONS.select{|k,v| k == params['section_type']}.first
      if @section
        @content_class = eval(@section[0].humanize)
      end
    end
end

app/views/main/_filters.html.haml
= javascript_include_tag "behavior/_filters"
= javascript_include_tag "tools/datepicker"
.filters
  %span= 'Фильтры'
  #data_filter
    %span= 'По дате'
    .date_block
      %label От
      %input{:name => 'start_at', :id => 'start_at'}
      .date_btn
    .date_block
      %label До
      %input{:name => 'end_at', :id => 'end_at'}
      .date_btn
  #type_filter
    - if types
      %span= 'По типу'
      = select_tag "type_id", options_from_collection_for_select(types, "id", "name"), {include_blank: true}

app/views/main/_form.html.haml
= form_for :element,  :as => :article, :url => main_form_path do |f|
  - if flash[:error] 
    .error
      = flash[:error]

  = f.label :category_id, 'Категория'
  = f.select :category_id, Category.all.map{|e| [e.name, e.id]}
  - if @thing and @thing.errors and @thing.errors[:category_id]
    .error_message= @thing.errors[:category_id].join(', ')
  
  %br
  
  = f.label "section", 'Раздел'
  = f.select "section", [["",""]] + @sections.map{|key, val| [val, key]}
  %br
  
    = f.label :name, 'Название'
    = f.text_field :name
    - if @thing and @thing.errors and @thing.errors[:name]
      .error_message= @thing.errors[:name].join(', ')
  %br
  
    = f.label :type_id, 'Тип'
    = f.select :type_id, ["",""]

    %img.plus#type_plus_btn{:src => '/images/plus.png'}
  #new_type_fields.hidden
    = text_field_tag(:type_name, nil, :id => 'type_name',:placeholder => 'введите название типа')
    = f.submit "Добавить", :id => 'add_type'
  - if @thing and @thing.errors and @thing.errors[:type_id]
    .error_message= @thing.errors[:type_id].join(', ')
  #article_fields.hidden
    %br
    = f.label 'article[autor]', 'Автор'
    = f.text_field 'article[autor]'
    %br
    = f.label 'article[body]', 'Содержание'
    = f.text_area 'article[body]'
    %br
    = f.label 'article[sources]', 'Источники'
    = f.text_area 'article[sources]'

  #event_fields.hidden
    %br
    = f.label 'event[start_at]', 'дата начала'
    = f.text_field 'event[start_at]'
    %br
    = f.label 'event[end_at]', 'дата конца'
    = f.text_field 'event[end_at]'
    %br
    = f.label 'event[description]', 'Описание'
    = f.text_area 'event[description]'
    %br
    = f.label 'event[web_links]', 'Источники'
    = f.text_area 'event[web_links]'

  #place_fields.hidden
    %br
    = f.label 'place[description]', 'Описание'
    = f.text_area 'place[description]'
    %br
    = f.label 'place[web_links]', 'Источники'
    = f.text_area 'place[web_links]'

  #project_fields.hidden
    %br
    = f.label 'project[description]', 'Содержание'
    = f.text_area 'project[description]'
    %br
    = f.label 'project[web_links]', 'Источники'
    = f.text_area 'project[web_links]'

  -# if @thing and @thing.errors and @thing.errors[:address_id]
    .error_message= @thing.errors[:address_id].join(', ')

  %br
  = f.label :picture, 'Фото'
  = f.file_field :picture
  %br
  = f.submit "Сохранить"

app/views/main/_map_includes.html.haml
= stylesheet_link_tag "map", :media => "all"
= "<script type='text/javascript' src='http://maps.googleapis.com/maps/api/js?key=#{Rails.application.config.maps_token}&sensor=false'></script>".html_safe
= javascript_include_tag "tools/map"

app/views/main/_sections.html.haml
.section_block
  %ul#sections 
    - sections.each do |key, val|
      %li{:id => "#{key}", :class => 'section'}= link_to val, section_path(key)

app/views/main/category_template.html.haml
= stylesheet_link_tag "application", :media => "all"
= stylesheet_link_tag "map", :media => "all"
= "<script type='text/javascript' src='http://maps.googleapis.com/maps/api/js?key=#{Rails.application.config.maps_token}&sensor=false'></script>".html_safe
= javascript_include_tag "tools/map"


.main_block
  #category_name
    %span= 'Название категории'
  .main_left
    .section_block
      %ul#sections 
        %li{:id => "#article_section"}= link_to 'Статьи', section_path('article')
        %li{:id => "#event_section"}= link_to 'События', section_path('event')
        %li{:id => "#place_section"}= link_to 'Места', section_path('place')
        %li{:id => "#project_section"}= link_to 'Проекты', section_path('project')
        %li{:id => "#person_section"}= link_to 'Лица', section_path('person')

    .filters
      %span= 'Фильтры'
      #data_filter
        %span= 'По дате'
        %label От
        %input{:name => 'date_from', :size => 5}
        %label До
        %input{:name => 'date_from', :size => 5}
      #type_filter
        %span= 'По типу'
        %input{:name => 'date_from', :size => 5, :type => :select}
  .main_right
    .view
      %span= "Вид"
      %img
      %img
      %img
    .content
      #map_container
      %ul.items.table
      %ul.items.line
      %ul.items.thumb
        %li.item
          %img.icon{:src => '/1.jpeg', :width=>"65", :height=>"65"}
          .item_info 
            %span.item_name Театр псих обльницы 1
            %p 
              сколько заклчённых
              сколько учавствовали в представлении
              где находиться и дата представления
          .description
            Такой замечательный театр, И не холодно совсем, и не дует из окна, и актёры профессоналы,
            только радоваться и лицезреть.
        %li.item
          %img.icon{:src => '/1.jpeg', :width=>"65", :height=>"65"}
          .item_info 
            %span.item_name Театр псих обльницы 1
            %p 
              сколько заклчённых
              сколько учавствовали в представлении
              где находиться и дата представления
          .description
            Такой замечательный театр, И не холодно совсем, и не дует из окна, и актёры профессоналы,
            только радоваться и лицезреть.
        %li.item
          %img.icon{:src => '/1.jpeg', :width=>"65", :height=>"65"}
          .item_info 
            %span.item_name Театр псих обльницы 1
            %p 
              сколько заклчённых
              сколько учавствовали в представлении
              где находиться и дата представления
          .description
            Такой замечательный театр, И не холодно совсем, и не дует из окна, и актёры профессоналы,
            только радоваться и лицезреть.

app/views/main/form.html.haml
= javascript_include_tag "tools/datepicker"
= javascript_include_tag "behavior/main/form_behavior"
= stylesheet_link_tag    "form", :media => "all"
#sections
  = link_to 'Статья', new_article_path(), :class => 'button', :id => 'article_section'
  = link_to 'Событие', new_event_path(), :class => 'section', :id => 'event_section'
  = link_to 'Место', new_place_path(), :class => 'section', :id => 'place_section'
  = link_to 'Проект', new_project_path(), :class => 'section', :id => 'project_section'




#article_fields.hidden
  = render :partial => 'articles/form', :locals => {:article => @article}
#event_fields.hidden
  = render :partial => 'events/form', :locals => {:event => @event}
#place_fields.hidden
  = render :partial => 'places/form', :locals => {:place => @place}
#project_fields.hidden
  = render :partial => 'projects/form', :locals => {:project => @project}

app/views/main/index.html.haml
=# javascript_include_tag "behavior/main/index"
.heder
  #header_name.left
    = link_to "Перекрёсток", root_path
  #weather.right
    = 'Картинка солнышка'
    = '+18C' 
    &deg;
    
.main_page_block
  = render :partial => 'sections', :locals => {:sections => @sections}

.team
  %span Команда
  %span
    %b Crossroad

app/views/main/map.html.haml
= javascript_include_tag "behavior/main/filter_behavior"
= javascript_include_tag "behavior/_filters"
= render :partial => '/main/map_includes'
= javascript_include_tag "behavior/categories/map_behavior"
= javascript_include_tag "behavior/main/map_page_behavior"
#filters.hidden{:data => "#{@filters.map{|e| e.to_json}}"}
.main_block
  #sections
    = render :partial => 'sections', :locals => {:sections => @sections}
  .main_left
    .category_block
      %span Категории
      - @categories.each do |category|
        .category
          %span.menu_item{:children => category.name + "children"}
            = link_to category.name, category_path(category), :class => 'category_item', :id => "category_#{category.id}", :data => category.id
          %ul{:id => category.name + "children"}
            - category.children.each do |child|
              %li= link_to child.name, category_path(child), :class => 'category_item', :id => "category_#{child.id}" , :data => child.id

    = render :partial => 'filters', :locals => {:types => @types}
  .main_right
    .content
      #map_container

app/views/main/search.html.haml
= javascript_include_tag "behavior/main/search"
.heder
  .left
    = "Днепровский Перекрёсток"
  .right
    = 'Картинка солнышка'
    = '+18C' 
    &deg;
    
= render :partial => 'sections', :locals => {:sections => @sections}

.main 	
  - @categories.each do |category|
    .category
      %span.menu_item{:children => category.name + "children"}
        = link_to category.name, category_path(category)
      %ul{:id => category.name + "children"}
        - category.children.each do |child|
          %li= link_to child.name, category_path(child)

.team
  %span Команда
  %span
    %b Crossroad

app/views/main/section.html.haml
= javascript_include_tag "behavior/main/section_page_behavior"
= javascript_include_tag "behavior/main/filter_behavior"
= render :partial => '/main/map_includes'
= javascript_include_tag "behavior/categories/map_behavior"
#filters.hidden{:data => "#{@filters.map{|e| e.to_json}}"}
.main_block
  #section_name
    %img.icon#sections_selector{:src => '/4.jpg', :width=>"35", :height=>"35"}
    %span= @section[1]
    = render :partial => 'sections', :locals => {:sections => @sections}
  .main_left
    .category_block
      %span Категории
      - @categories.each do |category|
        .category
          %span.menu_item{:children => category.name + "children"}
            = link_to category.name, category_path(category), :class => 'category_item', :id => "category_#{category.id}", :data => category.id
          %ul{:id => category.name + "children"}
            - category.children.each do |child|
              %li= link_to child.name, category_path(child), :class => 'category_item', :id => "category_#{child.id}" , :data => child.id

    = render :partial => 'filters', :locals => {:types => @types}
  .main_right
    .view
      .list_view_icon#view2
      .thumb_view_icon#view1
      .grid_view_icon#view3

      - unless ['person', 'article', 'project'].include? @section[0]
        %img.icon#map_show_btn{:src => '/6.png'}
    .content
      #map_block.hidden
        #map_close_btn
        #map_container
      .content_block{:id => "#{@section[0]}_content"}
        = render :partial => "/#{@section[0].pluralize}/content", :locals => {:content => @content}
        = paginate @content

app/views/main/template.html.haml
=# javascript_include_tag "behavior/main/index"
= stylesheet_link_tag    "template", :media => "all"
.heder
  .left
    = "Днепровский Перекрёсток"
  .right
    = 'Картинка солнышка'
    = '+18C' 
    &deg;

.sections
  %ul#sections
    %li#Article_section
      = '<a href="/section/Article">Статьи</a>'.html_safe
    %li#Event_section
      = '<a href="/section/Event">События</a>'.html_safe
    %li#Place_section
      = '<a href="/section/Place">Места</a>'.html_safe
    %li#Project_section
      = '<a href="/section/Project">Проекты</a>'.html_safe
    %li#Person_section
      = '<a href="/section/Person">Лица</a>'.html_safe

.main 	
  .category
    %span.menu_item{:children => "test1"}
      = link_to "Культура", "#"
    %ul{:id => "test1" }
      %li= link_to 'Театр', "#"
      %li= link_to 'Кино', "#"
      %li= link_to 'Музыка', "#"
      %li= link_to 'Литература', "#"
  

.team
  %span Команда
  %span
    %b Crossroad